apiVersion: v1
kind: Secret
metadata:
  name: influxdb-token
  namespace: kubeedge
type: Opaque
stringData:
  token: "LFxASUKbi1Q5rrprDzu70eDXqhpyJCv4UQnrCs1PJ17Q5Pvf3o2-Gg3yr3zq08RL4eYuCE_nR_BjMwMnOgIlTQ=="