apiVersion: v1
kind: Pod
metadata:
  name: busybox-test
  namespace: kubeedge
spec:
  nodeSelector:
    kubernetes.io/hostname: edge-server1
  containers:
  - name: busybox
    image: curlimages/curl:latest
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi